### ISSUE TITLE
Misplace ")" cause run error

### ISSUE THREAD

**Issue by katopz** [KTXSoftware/BunnyMark#1]
ios target run error at `BunnyMark/Kha/Backends/Kore/khacpp/src/hx/GCInternal.cpp`

![screen shot 2558-06-15 at 17 30 28](https://cloud.githubusercontent.com/assets/97060/8158195/1056dc10-1385-11e5-8df9-dc128f66a66f.png)

Workaround is move it back (remove new line)

**Comment by RobDangerous** [comment]
That looks like a multithreading error - an error which shows up at random times/locations. Did you use the Kha version pointed to by the BunnyMark repository or did you update Kha to the latest version?

**Comment by katopz** [comment]
Aw snap! I copy Kha from TPlayer because I don't want to fetch all Kha all over again 
and I don't think it will breaking simple test run but it seem like a bad idea.

Now I'm using BunnyMark repos without this issue.

Sorry!

**Comment by RobDangerous** [comment]
No prob :) Working a lot on Kha lately so stuff like that happens.
